### ISSUE TITLE
Sharing preview for social media

### ISSUE THREAD

**Issue by HKervadec** [MIDL-Conference/midl-website-2020#3]
As pointed out by @ieee8023 :
> Right now it is just text and there is no description so it doesn't look so nice. Can you make it show the logo and write a description? You can use this debugging tool:
> 
> https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2F2020.midl.io%2F

As far as I can tell, updating [_skeleton.html](https://github.com/MIDL-Conference/midl-website-theme/blob/master/layouts/_skeleton.html) seems to be the easiest option.

` _skeleton.html`
```html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        ...

        <meta property="og:title" content="{{ config.title|e }}">
        <meta property="og:image" content="{{ config.image|e }}">
        <meta property="og:description" content="{{ config.description|e }}">

        ...
    </head>
    ...
</html>
```
Notice that I went lazy with that one, and that if the values are not defined in the `website.yaml` it will provide properties with empty content ; that might actually break the parsing for the previous editions (as the empty values would replace the deduced values). Adding the missing properties to the previous editions would not take long.

`website.yaml`
```yaml
title: "MIDL 2020"
...
image: "/images/montreal-at-night.jpg"
description: "Third edition of the Medical Imaging with Deep Learning Conference (MIDL), Montréal"

...
```

What do you think ? Perhaps we could push things further later, by adding options to override those values on a page basis (instead of the current website basis).
